Internal Server Error: /api/tenants/
Traceback (most recent call last):
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column tenants_tenant.logo does not exist
LINE 1: ...nts_tenant"."email", "tenants_tenant"."password", "tenants_t...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 715, in to_representation
    return [
           ^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 384, in __iter__
    self._fetch_all()
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column tenants_tenant.logo does not exist
LINE 1: ...nts_tenant"."email", "tenants_tenant"."password", "tenants_t...
                                                             ^

"GET /api/tenants/ HTTP/1.1" 500 28881
Internal Server Error: /api/tenants/
Traceback (most recent call last):
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column tenants_tenant.logo does not exist
LINE 1: ...nts_tenant"."email", "tenants_tenant"."password", "tenants_t...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 715, in to_representation
    return [
           ^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 384, in __iter__
    self._fetch_all()
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column tenants_tenant.logo does not exist
LINE 1: ...nts_tenant"."email", "tenants_tenant"."password", "tenants_t...
                                                             ^

"GET /api/tenants/ HTTP/1.1" 500 28949
Internal Server Error: /api/tenants/
Traceback (most recent call last):
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column "logo" of relation "tenants_tenant" does not exist
LINE 1: ...t" ("id", "name", "api_key", "email", "password", "logo", "b...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/Repository/ConnectX/Backend/connectx_backend/tenants/views.py", line 34, in create
    tenant = serializer.save()
             ^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/rest_framework/serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/adane/Repository/ConnectX/Backend/connectx_backend/tenants/models.py", line 22, in save
    super().save(*args, **kwargs)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/query.py", line 1854, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1881, in execute_sql
    cursor.execute(sql, params)
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/adane/snap/code/190/.local/share/virtualenvs/Backend-OTU7wIHD/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column "logo" of relation "tenants_tenant" does not exist
LINE 1: ...t" ("id", "name", "api_key", "email", "password", "logo", "b...
                                                             ^

"POST /api/tenants/ HTTP/1.1" 500 30270
